version: '3.0'

services:

  ardupilot-copter-1of2:
    image: registry.dairkorea.com/github/ardupilot/sitl/copter:${TAG}
    container_name: ardupilot-copter-1of2
    restart: unless-stopped
    ports:      
      - ${LISTEN_TCP_PORT1}:5760/tcp
    stdin_open: true
    tty: true    
    entrypoint: [ "/ardupilot_entrypoint.sh" ]
    command:
      - sim_vehicle.py
      - --vehicle=ArduCopter
      #- --out=udp:192.168.201.10:14550
      #- --out=udp:192.168.0.9:14550
      - --wipe-eeprom
      - --sysid=1
      - --instance=0
      - --custom-location=35.280125,126.330111,3,0

  ardupilot-copter-2of2:
    image: registry.dairkorea.com/github/ardupilot/sitl/copter:${TAG}
    container_name: ardupilot-copter-2of2
    restart: unless-stopped
    depends_on:
      - ardupilot-copter-1of2
    ports:
      - ${LISTEN_TCP_PORT2}:5760/tcp
    stdin_open: true    
    tty: true    
    entrypoint: [ "/ardupilot_entrypoint.sh" ]
    command:  
      - sim_vehicle.py
      - --vehicle=ArduCopter
      #- --out=udp:192.168.201.10:14550
      #- --out=udp:192.168.0.9:14550
      - --wipe-eeprom
      - --sysid=2
      - --instance=1
      - --custom-location=35.280273,126.330332,3,0